name: Bug Report
description: File a bug report.
title: "Bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as many and as in depth details as possible.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expected-results
    attributes:
      label: What were the expected results?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Is this reproducible?
      description: If yes, please provide steps.